services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  review_service:
    build: ./review_service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    depends_on:
      - user_service

  conference_service:
    build: ./conference_service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
    depends_on:
      - user_service